# Configuration for GitHub Actions Labeler

# Specify label rules here
# Each rule consists of a label name and a list of conditions that need to be met in order to apply the label

feature:
  - head-branch: ['^feature', 'feature', '^feat', 'feat']

bug:
  - head-branch: ['^bugfix', 'bugfix', '^bug', 'bug']

hotfix:
  - head-branch: ['^hotfix', 'hotfix']

enhancement:
  - head-branch: ['^enhancement', 'enhancement', '^improvement', 'improvement']

documentation:
  - changed-files:
    - any-glob-to-any-file: ['docs/**', 'documentation/**', 'guides/*', '**/*.md']
