services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=loghub-database'
      - 'MONGO_INITDB_ROOT_PASSWORD=xps*NI_mYJr6PT*'
      - 'MONGO_INITDB_ROOT_USERNAME=loghub'
    ports:
      - '27017:27017'
