services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=loghub-database'
      - 'MONGO_INITDB_ROOT_PASSWORD=xps*NI_mYJr6PT*'
      - 'MONGO_INITDB_ROOT_USERNAME=loghub'
    ports:
      - '27017:27017'
  minio:
    image: 'docker.io/bitnami/minio:2022'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - 'MINIO_ROOT_USER=loghub'
      - 'MINIO_ROOT_PASSWORD=xps*NI_mYJr6PT*'
      - 'MINIO_DEFAULT_BUCKETS=loghub-bucket'
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.18'
    environment:
      - 'ELASTIC_PASSWORD=xps*NI_mYJr6PT*'
      - 'ELASTIC_USERNAME=loghub'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9200:9200'
      - '9300:9300'

volumes:
  minio_data:
    driver: local
