services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=loghub-database'
      - 'MONGO_INITDB_ROOT_PASSWORD=xps*NI_mYJr6PT*'
      - 'MONGO_INITDB_ROOT_USERNAME=loghub'
    ports:
      - '27017:27017'
  minio:
    image: 'docker.io/bitnami/minio:2022'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - 'MINIO_ROOT_USER=loghub'
      - 'MINIO_ROOT_PASSWORD=xps*NI_mYJr6PT*'
      - 'MINIO_DEFAULT_BUCKETS=loghub-bucket'

volumes:
  minio_data:
    driver: local
